### ISSUE TITLE
Badges are gone

### ISSUE THREAD

**Issue by alexandresaiz** [serverless/assets#2]
We used to put badges to promote serverless in our OS projects but this url is not serving the asset anymore:

http://public.serverless.com/badges/v3.svg

**Comment by mthenw** [comment]
Hey @alexandresaiz, thanks for letting us know. It has been fixed!

**Comment by dschep** [comment]
@mthenw that url is now the [v1](https://github.com/serverless/assets/blob/master/badges/serverless_badge_v1.svg) badge, not the [v3](https://github.com/serverless/assets/blob/master/badges/serverless_badge_v3.svg) badge afaict.

**Comment by mthenw** [comment]
@dschep you are right. Fixed. 3 versions are available. 

http://public.serverless.com/badges/v1.svg
http://public.serverless.com/badges/v2.svg
http://public.serverless.com/badges/v3.svg
